In [1]:
import numpy as np

# Create an ndarray x
x = np.array([1, 2, 3], np.int32)
print(x)

# Create a "slice" of x
y = x[:2]
print(y)

# Set the first element of y to be 6
y[0] = 6
print(y)

# Now the first element in x has changed to 6!
print(x)

[1 2 3]
[1 2]
[6 2]
[6 2 3]


In [2]:
# Create an ndarray x
x = [1, 2, 3]
print(x)

# Create a "slice" of x
y = x[:2]
print(y)

# Set the first element of y to be 6
y[0] = 6
print(y)

# Now the first element in x has changed to 6!
print(x)

[1, 2, 3]
[1, 2]
[6, 2]
[1, 2, 3]


In [3]:
import numpy as np

# Create an ndarray x
x = np.array([1, 2, 3], np.int32)
print(x)

# Create a "slice" of x
y = np.copy(x[:2])
print(y)

# Set the first element of y to be 6
y[0] = 6
print(y)

# Now the first element in x has changed to 6!
print(x)

[1 2 3]
[1 2]
[6 2]
[1 2 3]
