# Attributes of np.ndarray

codebasics [youtube](https://www.youtube.com/watch?v=a8aDcLk4vRc)

# Attributes

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

- ndarray.dtype

- ndarray.shape

- ndarray.size

- ndarray.ndim

- ndarray.itemsize

- ndarray.data

https://docs.scipy.org/doc/numpy/user/quickstart.html

<div align="center"><img src="img/Variable.png" width="50%"></div>

http://corochann.com/chainer-basic-module-introduction-1098.html

# dtype

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

##### list

- Each may have different data type

##### np.ndarray

- All have same data type

- Fast

In [1]:
import numpy as np

a = [1, 1.3, 'Hi']
b = [1.3, 1, 'David']

c = np.array([1, 1.3, 3.1])
d = np.array([1, 1.3, 3.1])

print(c.dtype)

float64


# shape

<div align="center"><img src="img/elsp_0105.png" width="50%"></div>

https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png

In [6]:
u = [1, '2', [3], (4,)]     

print(u)
print(type(u))
print(len(u))

[1, '2', [3], (4,)]
<class 'list'>
4


In [7]:
import numpy as np

if 0:
    u = np.array([1, 2, 3, 4]) 
elif 0:
    u = np.array((1, 2, 3, 4))
elif 0:
    u = np.arange(10)
elif 0:
    u = np.array([[-1., -0.6, -0.2], [0.2, 0.6, 1]])
elif 1:
    u = np.array([(-1., -0.6, -0.2), (0.2, 0.6, 1)])
    
print(u)
print(type(u))
print(len(u))
print()

print("dtype:    ", u.dtype)
print("shape:    ", u.shape)    
print("size:     ", u.size)
print("ndim:     ", u.ndim)
print("itemsize: ", u.itemsize)
print("data:     ", u.data)

[[-1.  -0.6 -0.2]
 [ 0.2  0.6  1. ]]
<class 'numpy.ndarray'>
2

dtype:     float64
shape:     (2, 3)
size:      6
ndim:      2
itemsize:  8
data:      <memory at 0x11347d480>


# How to change dtype

In [8]:
print(int(2.6))

2


In [9]:
print(float(2))

2.0


In [11]:
import numpy as np

u = np.array([[-1., -0.6, -0.2], [0.2, 0.6, 1]])

try:
    print(int(u))
except Exception as e:
    print(e)

only size-1 arrays can be converted to Python scalars


In [19]:
import numpy as np

if 0:
    # use astype method
    u = np.array([1., 2., 3., 4.]).astype(np.int32)
elif 0:
    # use astype method
    u = np.array([1., 2., 3., 4.]).astype(np.int64)
elif 0:
    # use dtype keyword
    u = np.array([1., 2., 3., 4.], dtype=np.int32)
elif 0:
    # use dtype keyword
    u = np.array([1., 2., 3., 4.], dtype=np.int64)
elif 0:
    # use dtype keyword
    u = np.linspace(0, 10, dtype=np.float32)
elif 0:
    # use dtype keyword
    u = np.linspace(0, 10, dtype=np.float64)
elif 1:
    # use dtype keyword
    u = np.eye(5, dtype=np.float32)
elif 1:
    # use dtype keyword
    u = np.eye(5, dtype=np.float64)

print(u)
print(u.dtype)
print(u.itemsize)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
float64
8


# How to change shape

In [27]:
if 0:
    # use reshape method
    u = np.array([[1, 2], [3, 4]]).reshape((4,))
elif 0:
    # use flatten method
    u = np.array([[1, 2], [3, 4]]).flatten()
elif 0:
    # use ravel method
    u = np.array([[1, 2], [3, 4]]).ravel()
elif 0:
    # reshape/flatten/ravel method는 오리지날을 건들이지 않고 reshape한 것을 리턴합니다. 
    # inplace=True도 작동하지 않아요. 
    # 리턴한 것을 받아야만 모양을 바꿀 수 있어요.
    u = np.array([[1, 2], [3, 4]])
    u.reshape((4,))
elif 0:
    # reshape/flatten/ravel method는 오리지날을 건들이지 않고 reshape한 것을 리턴합니다. 
    # inplace=True도 작동하지 않아요. 
    # 리턴한 것을 받아야만 모양을 바꿀 수 있어요.
    u = np.array([[1, 2], [3, 4]])
    u.flatten()
elif 1:
    # reshape/flatten/ravel method는 오리지날을 건들이지 않고 reshape한 것을 리턴합니다. 
    # inplace=True도 작동하지 않아요. 
    # 리턴한 것을 받아야만 모양을 바꿀 수 있어요.
    u = np.array([[1, 2], [3, 4]])
    u.ravel()
    
print(u)
print(u.shape)

[1 2 3 4]
(4,)


In [30]:
import numpy as np

np.random.seed(337)

u = np.random.uniform(0, 1, (3,))

if 0:
    # use np.expand_dims
    u1 = np.expand_dims(u, axis=0)
    u2 = np.expand_dims(u, axis=1)
elif 0:
    # use np.newaxis
    u1 = u[np.newaxis, :]
    u2 = u[:, np.newaxis]      
else:
    # use None
    u1 = u[None, :]
    u2 = u[:, None] 
    
print(u)
print(u.shape)
print()
    
print(u1)
print(u1.shape)
print()

print(u2)
print(u2.shape)

[0.79990679 0.15356741 0.5677806 ]
(3,)

[[0.79990679 0.15356741 0.5677806 ]]
(1, 3)

[[0.79990679]
 [0.15356741]
 [0.5677806 ]]
(3, 1)
