In [16]:
import numpy as np

x = np.array([1, 2, 3, 4]) # (4,)
print(x)

# x = np.reshape(x, (len(x), 1))
x = x.reshape((len(x), 1)) # (4,1)
print(x)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [17]:
y = np.array([0, 1, 2, 1])
# y = np.reshape(y, (1, len(y))) # (1,4)
y = y.reshape((1, len(y)))
print(y)

[[0 1 2 1]]


In [18]:
z = x + y
print(z)

[[1 2 3 2]
 [2 3 4 3]
 [3 4 5 4]
 [4 5 6 5]]


In [6]:
outer1 = x @ y # (4,1) @ (1,4) = (4,4)
outer2 = x.dot(y)
outer3 = np.matmul(x,y)
print(outer1)
print(outer2)
print(outer3)

[[0 1 2 1]
 [0 2 4 2]
 [0 3 6 3]
 [0 4 8 4]]
[[0 1 2 1]
 [0 2 4 2]
 [0 3 6 3]
 [0 4 8 4]]
[[0 1 2 1]
 [0 2 4 2]
 [0 3 6 3]
 [0 4 8 4]]


# inner product and outer product

In [9]:
u = np.array([1,2,3])
v = np.array([2,3,4])
inner_product = np.dot(u,v)
print(inner_product)
print(1*2+2*3+3*4)

20
20


In [12]:
u = np.array([1,2,3]).reshape((3,1))
v = np.array([2,3,4]).reshape((1,3))
outer_product = u@v
print(outer_product)

[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]
