# Componentwise Operations

In [5]:
import numpy as np

a = np.array([[1, 1], [2, 3]])
b = np.array([[1, 1], [2, 3]])

if 0:
    c = a + b
elif 0:
    c = a - b
elif 0:
    c = a * b
elif 1:
    c = a / b

print(c)

[[1. 1.]
 [1. 1.]]


In [9]:
import numpy as np

a = np.array([[1, 1], [2, 3]])

if 0:
    b = a**2
elif 0:
    b = np.power(a, 2)
elif 0:
    b = 2**a
elif 1:
    b = np.power(2, a)

print(b)

[[2 2]
 [4 8]]


In [11]:
import numpy as np

a = np.array([[1, 1], [2, 3]])

if 0:
    b = np.exp(a)
elif 1:
    b = np.log(a)

print(b)

[[0.         0.        ]
 [0.69314718 1.09861229]]


In [14]:
import numpy as np

a = np.array([[np.pi, 0.1], [0.2, 0.3]])

if 1:
    b = np.sin(a)
elif 1:
    b = np.cos(a)
elif 1:
    b = np.tan(a)
elif 1:
    b = np.arcsin(a)
elif 1:
    b = np.arccos(a)
elif 1:
    b = np.arctan(a)

print(b)

[[1.22464680e-16 9.98334166e-02]
 [1.98669331e-01 2.95520207e-01]]


In [16]:
import numpy as np

a = np.array([[3.1, 3.6], [0.2, 0.7]])

if 0:
    b = np.ceil(a)
elif 1:
    b = np.floor(a)
elif 1:
    b = np.round(a)

print(b)

[[3. 3.]
 [0. 0.]]


# Componentwise Operations with Broadcasting

<div align="center"><img src="https://www.python-course.eu/images/broadcasting_example_1.png" width="40%"></div>

In [19]:
import numpy as np

a = np.array([[11,12,13], [21,22,23], [31,32,33]])

if 0:
    b = np.array([1,2,3])
elif 0:
    b = np.array([[1,2,3]]) 
elif 1:
    b = np.array([[1],[2],[3]]) 
c = a*b

print(b)
print(c)

[[1]
 [2]
 [3]]
[[11 12 13]
 [42 44 46]
 [93 96 99]]


In [7]:
import numpy as np

a = np.array([[11,12,13], [21,22,23], [31,32,33]])

if 0:
    b = a + 2
elif 0:
    b = a - 2
elif 1:
    b = a * 2 
elif 1:
    b = a / 2 
elif 1:
    b = a % 2 
elif 1:
    b = a // 2 

print(a)
print(b)
print(c)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[22 24 26]
 [42 44 46]
 [62 64 66]]
[[11 12 13]
 [42 44 46]
 [93 96 99]]


문제. 
아래 그림을 만드는 코드를 완성하라.

<div align="center"><img src="img/Screen Shot 2018-11-27 at 10.59.03 AM.png" width="60%" height="30%"></div>

From CARL DOERSCH

```
import numpy as np
import matplotlib.pyplot as plt

z = np.random.normal(size=(2,100))
### put your code below
g = ### put your code here
### put your code above

plt.figure(1, figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(z[0,:],z[1,:],'ob',markersize=3)
plt.xlim((-4,4))
plt.ylim((-4,4))

plt.subplot(1,2,2)
plt.plot(g[0,:],g[1,:],'ob',markersize=3)
plt.xlim((-1.5,1.5))
plt.ylim((-1.5,1.5))

plt.show()
```