# How to make np.ndarray

codebasics [youtube](https://www.youtube.com/watch?v=rN0TREj8G7U)

<div align="center"><img src="img/Screen Shot 2018-08-08 at 3.55.26 PM.png" width="70%"></div>

Joe_James 
[youtube](https://www.youtube.com/watch?v=e60ItwlZTKM&t=18s) 
[github](https://github.com/joeyajames/Python)

# np.ndarray 만드는 방법

In [39]:
import numpy as np

if 0:
    a = np.array([0,1,2,3,4,5,6,7,8,9])
elif 0:
    a = np.array([[-1., -0.6, -0.2], [0.2, 0.6, 1.]])
elif 0:
    a = np.arange(10)
elif 0:
    a = np.linspace(1,10)
elif 0:
    a = np.zeros((3,4))
elif 0:
    a = np.ones((3,4))
elif 0:
    a = np.empty((3,4))
elif 0:
    u = np.array([[-1., -0.6, -0.2], [0.2, 0.6, 1.]])
    a = np.zeros_like(u)
elif 0:
    u = np.array([[-1., -0.6, -0.2], [0.2, 0.6, 1.]])
    a = np.ones_like(u)
elif 0:
    u = np.array([[-1., -0.6, -0.2], [0.2, 0.6, 1.]])
    a = np.empty_like(u)
elif 0:
    a = np.eye(2)
elif 0:
    a = np.eye(2,3)
elif 0:
    a = np.diag([1,2,3])
elif 1:
    a = np.full((2, 2), 7.)

print(a)
print(type(a))
print(a.dtype)
print(a.shape)

[[7. 7.]
 [7. 7.]]
<class 'numpy.ndarray'>
float64
(2, 2)


# np.ndarray는 list와 매우 비슷하다

In [23]:
import numpy as np 

a = np.array([0,1,2,3,4,5,6,7,8,9])

print(a)
print(a[0])
print(a[1])
print(a[3:7])

[0 1 2 3 4 5 6 7 8 9]
0
1
[3 4 5 6]
