In [3]:
gene0 = [100, 200]
gene1 = [50, 0]
gene2 = [350, 100]
expression_data = [gene0, gene1, gene2]

print(expression_data)
print(type(expression_data))

[[100, 200], [50, 0], [350, 100]]
<class 'list'>


In [12]:
import numpy as np

gene0 = [100, 200]
gene1 = [50, 0]
gene2 = [350, 100]

A = np.array([gene0, gene1])
B = np.array([gene0, gene2])

print(A)
print(type(A))

[[100 200]
 [ 50   0]]
<class 'numpy.ndarray'>


In [13]:
print(A.T)
print(np.transpose(A))

[[100  50]
 [200   0]]
[[100  50]
 [200   0]]


In [22]:
u = np.array([0, 1, 2])

print(u)
print(u.T)
print(u.ndim)

[0 1 2]
[0 1 2]
1


In [24]:
u = np.array([[0, 1, 2]])

print(u)
print(u.T)
print(u.ndim)
print(u.T.ndim)

[[0 1 2]]
[[0]
 [1]
 [2]]
2
2


In [25]:
print(np.linalg.inv(A))
print(A@np.linalg.inv(A))
print(np.linalg.inv(A)@A)

[[ 0.     0.02 ]
 [ 0.005 -0.01 ]]
[[  1.00000000e+00  -4.16333634e-17]
 [  0.00000000e+00   1.00000000e+00]]
[[  1.00000000e+00   0.00000000e+00]
 [ -1.04083409e-17   1.00000000e+00]]


In [16]:
print(A@B)
print(A.dot(B))
print(np.matmul(A, B))

[[80000 40000]
 [ 5000 10000]]
[[80000 40000]
 [ 5000 10000]]
[[80000 40000]
 [ 5000 10000]]


In [28]:
print(np.linalg.det(A))
print(np.linalg.cond(A))
print(np.linalg.eig(A))

-10000.0
5.05206097987
(array([ 161.80339887,  -61.80339887]), array([[ 0.95542256, -0.77743752],
       [ 0.29524181,  0.62896017]]))


In [32]:
la, v = np.linalg.eig(A)
print(la)
print(v)

[ 161.80339887  -61.80339887]
[[ 0.95542256 -0.77743752]
 [ 0.29524181  0.62896017]]


$$
{\bf A}[{\bf v}_1 {\bf v}_2]
=[\lambda_1{\bf v}_1 \lambda_2{\bf v}_2]
=[{\bf v}_1 {\bf v}_2]
\left[\begin{array}{cc}
\lambda_1&0\\
0&\lambda_2
\end{array}\right]
$$

In [39]:
print(A@v[:,0]) # v[:,0].ndim=1
print(la[0]*v[:,0])

[ 154.59061809   47.77112816]
[ 154.59061809   47.77112816]
[ 0.95542256  0.29524181]


In [35]:
print(A@v[:,1])
print(la[1]*v[:,1])

[ 48.04828145 -38.87187624]
[ 48.04828145 -38.87187624]


In [38]:
print(A@v)
print(v@np.diag(la))

[[ 154.59061809   48.04828145]
 [  47.77112816  -38.87187624]]
[[ 154.59061809   48.04828145]
 [  47.77112816  -38.87187624]]
