# np.max vs np.maximum

<div align="center"><img src="img/Screen Shot 2019-02-15 at 5.21.22 PM.png" width="80%"></div>

https://stackoverflow.com/questions/33569668/numpy-max-vs-amax-vs-maximum

In [1]:
import numpy as np

a = np.array([3,2,5])
print(np.max(a))

5


In [2]:
import numpy as np

a = np.array([3,2,5])
print(np.maximum(a,4))

[4 4 5]


# axis

In [5]:
import numpy as np

a = np.array([[3,2,5],[1,2,7]])
print(a)
print()

print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))

[[3 2 5]
 [1 2 7]]

7
[3 2 7]
[5 7]


# np.max vs np.nanmax

In [6]:
import numpy as np

a = np.array([np.nan,2,5])
print(np.max(a))

nan


/anaconda3/lib/python3.5/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [7]:
import numpy as np

a = np.array([np.nan,2,5])
print(np.nanmax(a))

5.0


In [8]:
import numpy as np

a = np.array([[np.nan,2,5],[1,2,7]])
print(a)
print()

print(np.max(a))
print(np.max(a, axis=0))
print(np.max(a, axis=1))

[[nan  2.  5.]
 [ 1.  2.  7.]]

nan
[nan  2.  7.]
[nan  7.]


/anaconda3/lib/python3.5/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


In [9]:
import numpy as np

a = np.array([[np.nan,2,5],[1,2,7]])
print(a)
print()

print(np.nanmax(a))
print(np.nanmax(a, axis=0))
print(np.nanmax(a, axis=1))

[[nan  2.  5.]
 [ 1.  2.  7.]]

7.0
[1. 2. 7.]
[5. 7.]


# np.maximum vs np.fmax

In [10]:
import numpy as np

a = np.array([np.nan,2,5])
print(np.maximum(a,4))

[nan  4.  5.]


/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in maximum
  after removing the cwd from sys.path.


In [11]:
import numpy as np

a = np.array([np.nan,2,5])
print(np.fmax(a,4))

[4. 4. 5.]
