In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(a)
print(type(a))
print(a.shape)
print(a.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
1


In [4]:
import numpy as np

gene0 = [100, 200]
gene1 = [50, 0]
gene2 = [350, 100]
a = np.array([gene0, gene1, gene2])

print(a)
print(type(a))
print(a.shape)
print(a.ndim)

[[100 200]
 [ 50   0]
 [350 100]]
<class 'numpy.ndarray'>
(3, 2)
2


In [5]:
import numpy as np

gene0 = [100, 200]
gene1 = [50, 0]
A = np.array([gene0, gene1]) # (2, 2)
x = np.array(gene0).reshape((2,1)) # (2,) ---> (2, 1)
Ax = A@x # (2, 1)

print(Ax)
print(type(Ax))
print(Ax.shape)
print(Ax.ndim)

[[50000]
 [ 5000]]
<class 'numpy.ndarray'>
(2, 1)
2


In [6]:
import numpy as np

gene0 = [100, 200]
gene1 = [50, 0]
A = np.array([gene0, gene1]) # (2, 2)
x = np.array(gene0) # (2,) 
Ax = A@x # (2, 1)

print(Ax)
print(type(Ax))
print(Ax.shape)
print(Ax.ndim)

[50000  5000]
<class 'numpy.ndarray'>
(2,)
1
