In [1]:
a = [0,1,2,3,4,5,6,7,8,9]

print(a[1])
print(a[1:5])
print(a[-2])
print(a[:5])
print(a[1:])
print(a[:5:2])
print(a[1::2])
print(a[::-1])

1
[1, 2, 3, 4]
8
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4]
[1, 3, 5, 7, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [2]:
a = 'I am happy now!'

print(a[1])
print(a[1:5])
print(a[-2])
print(a[:5])
print(a[1:])
print(a[:5:2])
print(a[1::2])
print(a[::-1])

 
 am 
w
I am 
 am happy now!
Ia 
 mhpynw
!won yppah ma I


In [3]:
import numpy as np

a = np.array([0,1,2,3,4,5,6,7,8,9])

print(a[1])
print(a[1:5])
print(a[-2])
print(a[:5])
print(a[1:])
print(a[:5:2])
print(a[1::2])
print(a[::-1])

1
[1 2 3 4]
8
[0 1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[0 2 4]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [8]:
a = [[0,1,2],[1,2,3]]

print(a[1])
print(a[1][0])
# print(a[1,0]) # TypeError: list indices must be integers or slices, not tuple

[1, 2, 3]
1


TypeError: list indices must be integers or slices, not tuple

In [7]:
import numpy as np

a = np.array([[0,1,2],[1,2,3]])

print(a)
print()

print(a[0]) # a[0] = a[0,:] 
print(a[1]) # a[1] = a[1,:] 
print(a[1,:])
print(a[:,1])
print(a[1,0])

[[0 1 2]
 [1 2 3]]

[0 1 2]
[1 2 3]
[1 2 3]
[1 2]
1
