# One Hot Encoding

$$\begin{array}{llllllllllll}
0&\rightarrow&[&1&0&0&0&]\\
1&\rightarrow&[&0&1&0&0&]\\
2&\rightarrow&[&0&0&1&0&]\\
3&\rightarrow&[&0&0&0&1&]\\
\end{array}$$

In [2]:
import numpy as np

print(np.eye(4))
print()
print(np.eye(4)[2])
print()
print(np.eye(4)[[0,0,3]])
print()
print(np.eye(4)[np.array([0,0,3])])
print()
print(np.eye(4)[[0,0,3]].astype(np.int32))
print()
print(np.eye(4)[[0,0,3]].astype(np.float32))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[0. 0. 1. 0.]

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]

[[1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]]

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [6]:
import numpy as np

def one_hot(list_or_1d_array, num_states):
    # list_or_1d_array = [0,0,3] or np.array([0,0,3]) 
    # num_states = 4
    return np.eye(num_states)[list_or_1d_array].astype(np.int32)

print(one_hot(list_or_1d_array=[0,0,3], num_states=4))
print()
print(one_hot(list_or_1d_array=np.array([0,0,3]), num_states=4))
print()
print(one_hot([0,0,3], 4))
print()
print(one_hot(np.array([0,0,3]), 4))

[[1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]]

[[1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]]

[[1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]]

[[1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]]
