# Solving System of Linear Equations

PHYS_250 [youtube](https://www.youtube.com/watch?v=hxuYzgwuthg&t=892s)

In [31]:
import numpy as np
import scipy.linalg as sl

np.random.seed(337)

# Ax = b
A = np.random.normal(0,1,(3,3))
x = np.random.normal(0,1,(3,1)) 
b = A@x

# x = A\b
if 0: 
    x_sol = np.linalg.solve(A,b)
elif 1:
    x_sol = sl.solve(A,b)

print(x)
print()

print(x_sol)

[[-0.69957044]
 [-0.34232785]
 [ 0.52621269]]

[[-0.69957044]
 [-0.34232785]
 [ 0.52621269]]


# np.eye

In [9]:
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.eye.html

import numpy as np

if 0:
    A = np.eye(5)
elif 0:
    A = np.eye(5, k=1)
elif 0:
    A = np.eye(5, k=2)
elif 0:
    A = np.eye(5, k=-1)
elif 1:
    A = np.eye(5, k=-2)
    
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [41]:
# https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.diag.html

import numpy as np

if 0:
    A = np.diag([1,2,3,4,5])
elif 0:
    A = np.diag([1,2,3,4,5], k=1)
elif 0:
    A = np.diag([1,2,3,4,5], k=2)
elif 0:
    A = np.diag([1,2,3,4,5], k=-1)
elif 1:
    A = np.diag([1,2,3,4,5], k=-2)
    
print(A)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]]


In [5]:
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.spdiags.html

import scipy.sparse as ss

if 0:
    A = ss.spdiags([1,2,3,4,5], 0, 5, 5)
elif 0:
    A = ss.spdiags([1,2,3,4,5], 1, 5, 5)
elif 0:
    A = ss.spdiags([1,2,3,4,5], 2, 5, 5)
elif 0:
    A = ss.spdiags([1,2,3,4,5], -1, 5, 5)
elif 1:
    A = ss.spdiags([1,2,3,4,5], -2, 5, 5)
    
print(A)
print()

print(A.toarray())
print()

print(A)

  (2, 0)	1
  (3, 1)	2
  (4, 2)	3

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]]

  (2, 0)	1
  (3, 1)	2
  (4, 2)	3
