# Various Matrix Operations 

In [1]:
import numpy as np

np.random.seed(337)

A = np.random.uniform(0., 1., (2,2))
print(A)
print()

det_A = np.linalg.det(A) # determinant
print(det_A)
print()

cond_A = np.linalg.cond(A) # condition number
print(cond_A)
print()

trace_A = np.trace(A) # trace
print(trace_A)

[[0.79990679 0.15356741]
 [0.5677806  0.04969421]]

-0.04744186416770812

20.783235793533443

0.8496009992076644


In [2]:
import numpy as np

np.random.seed(337)

A = np.random.uniform(0., 1., (2,2))
print(A)
print()

inv_A = np.linalg.inv(A) # inverse
print(inv_A)
print()

pinv_A = np.linalg.pinv(A) # psudo-inverse
print(pinv_A)

[[1 1]
 [1 1]]

[[0.25 0.25]
 [0.25 0.25]]


In [3]:
import numpy as np

np.random.seed(337)

A = np.random.uniform(0., 1., (2,2))
print(A)
print()

A_T1 = A.T # transpose
print(A_T1)
print()

A_T2 = np.transpose(A) # transpose
print(A_T2)

[[0.79990679 0.15356741]
 [0.5677806  0.04969421]]

[[0.79990679 0.5677806 ]
 [0.15356741 0.04969421]]

[[0.79990679 0.5677806 ]
 [0.15356741 0.04969421]]
