In [10]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
c = np.concatenate((a, b.T), axis=1)
# c = np.concatenate((a, b), axis=None)

print(a)
print(b)
print(c)

[[1 2]
 [3 4]]
[[5 6]]
[[1 2 5]
 [3 4 6]]


```numpy.r_[array[], array[]]```
This is a simple way to concatenate any number of array slices along row axis. 

```numpy.c_[array[], array[]]```
This is a simple way to concatenate any number of array slices along column axis. 

https://stackoverflow.com/questions/30597869/what-does-np-r-do-numpy

In [19]:
import numpy as np

a = np.arange(9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
print(a)
print(b)
print()

sliced_a = a[1,1:3]
sliced_b = b[1,1:3]
c1 = np.concatenate((sliced_a, sliced_b)) 
c2 = np.hstack((sliced_a,sliced_b))
c3 = np.r_[sliced_a,sliced_b]
print(sliced_a)
print(sliced_b)
print(c1)
print(c2)
print(c3)
print()

sliced_a = a[1,1:3]
sliced_b = b[1,1:3]
c1 = np.concatenate((sliced_a.reshape((1,-1)), sliced_b.reshape((1,-1))), axis = 0).T
c2 = np.vstack((sliced_a,sliced_b)).T
c3 = np.c_[sliced_a,sliced_b]
print(sliced_a)
print(sliced_b)
print(c1)
print(c2)
print(c3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]

[4 5]
[14 15]
[ 4  5 14 15]
[ 4  5 14 15]
[ 4  5 14 15]

[4 5]
[14 15]
[[ 4 14]
 [ 5 15]]
[[ 4 14]
 [ 5 15]]
[[ 4 14]
 [ 5 15]]


In [28]:
import numpy as np

x = np.random.normal(size=(10,3))
#A = np.r_[np.ones(3).reshape((1,-1)), x]
A = np.c_[np.ones(10).reshape((-1,1)), x]
print(x)
print(A)

[[-1.35647608 -0.41018247 -0.60506871]
 [-1.99390954 -0.2128536  -2.46853354]
 [ 1.46115896 -0.3095297  -0.12914694]
 [ 0.75505084 -0.59263306  0.38772376]
 [-1.54699176  1.02812879 -0.68746898]
 [ 1.28396106 -1.40472966  1.25268532]
 [-0.75291786  0.50646356 -0.88758717]
 [-0.75336582  0.98793086 -0.57071182]
 [-0.66940084  0.20489547  2.25436846]
 [ 1.62163928 -0.04610234 -0.70078241]]
[[ 1.         -1.35647608 -0.41018247 -0.60506871]
 [ 1.         -1.99390954 -0.2128536  -2.46853354]
 [ 1.          1.46115896 -0.3095297  -0.12914694]
 [ 1.          0.75505084 -0.59263306  0.38772376]
 [ 1.         -1.54699176  1.02812879 -0.68746898]
 [ 1.          1.28396106 -1.40472966  1.25268532]
 [ 1.         -0.75291786  0.50646356 -0.88758717]
 [ 1.         -0.75336582  0.98793086 -0.57071182]
 [ 1.         -0.66940084  0.20489547  2.25436846]
 [ 1.          1.62163928 -0.04610234 -0.70078241]]
