In [1]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]] 
c = a@b
print(c)

TypeError: unsupported operand type(s) for @: 'list' and 'list'

In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) 
c = a@b
print(c)

[[19 22]
 [43 50]]


$$
\left[\begin{array}{c}
1&2\\
3&4
\end{array}\right]
\left[\begin{array}{c}
5&6\\
7&8
\end{array}\right]
=
\left[\begin{array}{c}
19&22\\
43&50
\end{array}\right]
$$

In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]]) 
#c = a@b
#c = a.dot(b)
c = np.dot(a,b)
print(c)

[[19 22]
 [43 50]]


$$
\left[\begin{array}{cc}
1&2\\
3&4
\end{array}\right]
\left[\begin{array}{cc}
5\\
7
\end{array}\right]
=
\left[\begin{array}{cc}
19\\
43
\end{array}\right]
$$

In [6]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5],[7]]) 
c = a@b
# c = a.dot(b)
# c = np.dot(a,b)
print(c)

[[19]
 [43]]


In [8]:
import numpy as np
a = np.array([[5],[7]])
b = a.T
print(a)
print(b)

[[5]
 [7]]
[[5 7]]


In [9]:
import numpy as np
a = np.array([5,7])
b = a.T
print(a)
print(b)

[5 7]
[5 7]


$$
\left[\begin{array}{cc}
1&2
\end{array}\right]
\left[\begin{array}{cc}
5&6\\
7&8
\end{array}\right]
=
\left[\begin{array}{cc}
19&22
\end{array}\right]
$$

In [7]:
import numpy as np
a = np.array([[1,2]])
b = np.array([[5,6],[7,8]]) 
c = a@b
# c = a.dot(b)
# c = np.dot(a,b)
print(c)

[[19 22]]


In [10]:
import numpy as np
a = np.array([[1,2]])
b = a.T
print(a)
print(b)

[[1 2]]
[[1]
 [2]]


In [11]:
import numpy as np
a = np.array([1,2])
b = a.T
print(a)
print(b)

[1 2]
[1 2]
